### ISSUE TITLE
Crashing when set date/location

### ISSUE THREAD

**Issue by synfinatic** [synfinatic/alpacascope#17]
Happens from SkySafari with Nexstar with "set date/location" feature enabled.

```
./dist/alpacascope-0.0.6-darwin-amd64
INFO[0000] Looking for Alpaca Remote Server locally on port 11111...
INFO[0000] No local Alpaca Remote Servers found
INFO[0000] Discovered Alpaca Server on 172.16.1.115:11111
INFO[0000] Starting SkyFi Discovery service on UDP/4031
INFO[0000] Connected to telescope 0: CPWI_ASCOM_Telescope
INFO[0000] Waiting for nexstar clients on 0.0.0.0:4030
ERRO[0033] Error talking to scope: 1024: Property write UTCDate is not implemented in this driver.
panic: runtime error: index out of range [7] with length 7

goroutine 21 [running]:
main.NexstarToLatLong(...)
	/Users/aturner/go/src/github.com/synfinatic/alpacascope/cmd/nexstar.go:313
main.nexstar_command(0xc00000e6a0, 0x9, 0xc0000b3000, 0x400, 0x400, 0x0, 0x0, 0x8)
	/Users/aturner/go/src/github.com/synfinatic/alpacascope/cmd/nexstar.go:175 +0x1813
main.handleNexstar(0x13ef500, 0xc00009c070, 0xc00000e6a0)
	/Users/aturner/go/src/github.com/synfinatic/alpacascope/cmd/nexstar.go:24 +0x14c
created by main.main
	/Users/aturner/go/src/github.com/synfinatic/alpacascope/cmd/main.go:170 +0xb05
```

**Comment by synfinatic** [comment]
[SkySafariScopeLog-2021-01-21-22-37-50.txt](https://github.com/synfinatic/alpacascope/files/5854009/SkySafariScopeLog-2021-01-21-22-37-50.txt)
